#!/usr/bin/env zsh
#
# STOW_FOLDERS="bin,i3,netflix,nvim,personal,tmux,uwuntu,xkb,zsh"
STOW_FOLDERS="aerospace, karabiner, sketchybar, bin, dunst, i3, ghostty, nvim, picom, screenlayout, tmux, zsh, skhdrc"
DOTFILES=$HOME/.dotfiles
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd

